sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hrdrmjfCjGGec2cOVVxsPRW0XnwNyRrINfabH0T0chRGYiZB1vt+OGU3gPilO8i8Ls/sHzfTHoZethUbp2wd1Y6SVaNrj3aIQ3KybXZl4dP/Y5AC6/jz2lL55sMqHFZjSM7CWpoCMiHAE/CU/IGHzdVZhzJzWQIWMc5xVGwOGwxiUinTqmryjSoS0MF0ZEdr2lJvzgJSQumaY1tTvPbT50JvY9ObyQHepq8R81X9Ss4QPvesOvbxJcv7ioGBBnKhn2H/9b6arU2p/WSuEq70WPBj3kL3Kyh1MQxIFL70AIZSPdQohdw8Eg+s+hC57/OsRHL0SDw1x/NFom33ke/r/FF2WLizPnTgL3IN6xFnr0jHJPDxnA2qSFmbMTW1Ms2QLR2OuI9uLCAbaDoGXI+2G+nHfE+zp5z/smnsLCTnwqFC3LLlEt6cYnF6YTv+KYGg9P0zjvW3dD4Qtb1YpiA/HWm9ejT2KVs+G+vfPpAZY9nbMjKM584Q9A/Lfuo6XIW0gmlBXrzZTGvYK+OgzRA5yyDP2qHmE5ZqLK/yd63OvPa6msZ9b3lRaGrlkp5d+5xQtH+WjzbKDlZmHdd1BtpuzFAnByhdAZGv9I6RVNqhqlRN37Y1fJjl5zkYkTjC3gpji7RIJHR/4mauWTMwjTThy/MCIAoVMYOpUW3Y/O9mvic=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Five-Thousand-Miles-Underground--Or-the-Mystery-of-the-Centre-of-the-Earth_4994
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy